"""Independent counterexamples for pinned, unapproved what-if calculations.

All observations and reviewer attribution below are synthetic test fixtures.
No real tissue annotations or approval records are generated by these tests.
"""
from copy import deepcopy
import hashlib
import json
from pathlib import Path

import pytest

from spatial_collab import sensitivity
from spatial_collab.replay import verify_bundle
from spatial_collab.store import Project, SpatialError, _hash


@pytest.fixture
def factory(tmp_path):
    def create(scope=None, suffix="project"):
        metadata = {"name": "synthetic sensitivity review", "slice_id": "s", "coordinate_system": "s-xy",
                    "units": "micrometer", "source_kind": "synthetic", "panel_genes": ["G"],
                    "import_scope": scope if scope is not None else {
                        "kind": "spatial_window", "units": "micrometer", "sampling": "none",
                        "bounds": [-10, -10, 40, 40], "selected_observation_count": 4,
                        "source_observation_count": 100,
                        "selection_rule": "all cell centroids with xmin <= x <= xmax and ymin <= y <= ymax"}}
        return Project.create(tmp_path / suffix, [
            {"cell_id": "source", "x": 0, "y": 0, "label": "T", "counts": {"G": 2}},
            {"cell_id": "near_target", "x": 1, "y": 0, "label": "B", "counts": {}},
            {"cell_id": "far_target", "x": 20, "y": 0, "label": "B", "counts": {}},
            {"cell_id": "edge_other", "x": 39, "y": 0, "label": "O", "counts": {}}], metadata)
    return create


def setup(project, ids=None):
    revision = project.summary()["head_revision"]
    selection = project.set_selection(revision, cell_ids=ids or ["source"])
    return revision, selection["selection_id"]


def variant(name="relabel_near", ids=None, changes=None):
    return {"name": name, "cell_ids": ids or ["near_target"], "changes": changes or {"label": "O"},
            "rationale": "Synthetic alternative assumption; no human decision implied"}


def run(project, variants=None, radii=None, ids=None, **kwargs):
    revision, selection = setup(project, ids)
    return sensitivity.run_sensitivity(project, revision, selection, variants or [variant()],
                                       radii or [2.0], "T", "B", **kwargs)


def test_variants_restart_from_baseline_and_off_roi_neighbors_remain_eligible(factory):
    project = factory()
    before = deepcopy(project.cells())
    result = run(project, [variant(), variant("exclude_far", ["far_target"], {"included": False})])
    relabel, exclusion = result["results"]
    assert relabel["before"] == exclusion["before"]
    assert relabel["after"]["observed_fraction"] == 0
    assert exclusion["after"]["observed_fraction"] == 1  # near target did not inherit variant one's relabel
    assert exclusion["after"]["null_fraction"] == 0.5
    assert relabel["changed_in_analysis_roi"] == exclusion["changed_in_analysis_roi"] == 0
    assert relabel["actual_changed_count"] == exclusion["actual_changed_count"] == 1
    assert project.cells() == before
    assert project.context()["latest_proposal_id"] is None
    assert project.summary()["revision_count"] == 1
    assert result["base_revision"] == result["target_revision"]
    assert result["researcher_approval"] == "NOT_REQUESTED_HYPOTHESIS_ONLY"


def test_new_counterfactual_source_near_boundary_requires_union_coverage(factory):
    project = factory()
    result = run(project, [variant("new_source", ["edge_other"], {"label": "T"})],
                 ids=["source", "edge_other"])
    assert result["results"][0]["before"]["graph"]["source_count"] == 1
    assert result["results"][0]["after"]["graph"]["source_count"] == 2
    assert result["results"][0]["neighbor_coverage"] == "window_boundary_may_truncate_neighbors"


@pytest.mark.parametrize("scope_change", [
    {"sampling": "random"}, {"kind": "selected_cell_ids"}, {"units": "pixel"},
    {"selected_observation_count": 3}, {"bounds": [-10, -10, 25, 40]},
    {"selection_rule": "first 4 source observations"},
])
def test_geometric_margin_does_not_certify_incomplete_window(factory, scope_change):
    project = factory()
    scope = deepcopy(project.summary()["metadata"]["import_scope"])
    scope.update(scope_change)
    project = factory(scope, "counterexample")
    try:
        result = run(project)
    except SpatialError:
        return  # Explicit rejection is also safer than false coverage.
    assert result["results"][0]["neighbor_coverage"] != "complete_for_radius_within_declared_window"


def test_roi_induced_truncation_is_explicit_without_crop_metadata(factory):
    project = factory({})
    result = run(project, ids=["source", "near_target"], graph_scope="roi_induced")
    assert result["results"][0]["neighbor_coverage"] == "ROI_induced_neighbors_intentionally_truncated"


def test_selection_source_hash_must_match_pinned_source(factory, monkeypatch):
    project = factory()
    revision, selection_id = setup(project)
    selected = project.get_selection(selection_id)
    selected["source_sha256"] = "0" * 64
    monkeypatch.setattr(project, "get_selection", lambda _: deepcopy(selected))
    with pytest.raises(SpatialError, match="source|Source"):
        sensitivity.run_sensitivity(project, revision, selection_id, [variant()], [2.0], "T", "B")
    assert project.summary()["runs"] == []


def test_late_resource_failure_saves_no_partial_grid_or_revision(factory, monkeypatch):
    project = factory()
    revision, selection_id = setup(project)
    original = sensitivity._evaluate
    calls = 0

    def bounded(*args, **kwargs):
        nonlocal calls
        calls += 1
        if calls == 3:
            raise SpatialError("Synthetic grid resource limit")
        return original(*args, **kwargs)

    monkeypatch.setattr(sensitivity, "_evaluate", bounded)
    with pytest.raises(SpatialError, match="resource limit"):
        sensitivity.run_sensitivity(project, revision, selection_id, [variant()], [2.0, 5.0], "T", "B")
    assert project.summary()["runs"] == []
    assert project.summary()["revision_count"] == 1
    assert project.context()["latest_proposal_id"] is None


def test_historical_grid_replays_actual_cells_without_counterfactual_revision(factory):
    project = factory()
    revision, selection_id = setup(project)
    proposal = project.propose_revision(revision, selection_id, {"region": "synthetic fixture"}, "synthetic test")
    head = project.apply_revision(proposal["proposal_id"], revision, "Synthetic test driver", True)["revision_id"]
    result = sensitivity.run_sensitivity(project, revision, selection_id, [variant()], [2.0], "T", "B")
    assert result["stale"] and project.summary()["head_revision"] == head
    bundle = Path(project.export_bundle(result["run_id"])["export_path"])
    source_cells = project.cells(revision)
    assert json.loads((bundle / "base_cells.json").read_text()) == source_cells
    assert json.loads((bundle / "target_cells.json").read_text()) == source_cells
    before = {path.name: path.read_bytes() for path in bundle.iterdir()}
    assert verify_bundle(bundle)["recompute_matches"]
    assert {path.name: path.read_bytes() for path in bundle.iterdir()} == before


def _rewrite(folder, name, value):
    content = (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()
    (folder / name).write_bytes(content)
    manifest = json.loads((folder / "manifest.json").read_text())
    manifest["files"][name] = {"sha256": hashlib.sha256(content).hexdigest(), "bytes": len(content)}
    (folder / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")


def test_rehashed_claim_of_human_approval_is_not_a_matching_recomputation(factory):
    project = factory()
    result = run(project)
    bundle = Path(project.export_bundle(result["run_id"])["export_path"])
    saved = json.loads((bundle / "result.json").read_text())
    saved["researcher_approval"] = "APPROVED"  # adversarial fixture, never a real attribution
    _rewrite(bundle, "result.json", saved)
    provenance = json.loads((bundle / "provenance.json").read_text())
    provenance["run_sha256"] = _hash(saved)
    _rewrite(bundle, "provenance.json", provenance)
    receipt = verify_bundle(bundle)
    assert receipt["integrity_verified"] and not receipt["recompute_matches"]
    assert "researcher_approval" in receipt["mismatched_fields"]
